"""
Django settings for travelplanner project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings///
"""

from pathlib import Path
import os
from azure.storage.blob import BlobServiceClient
from django.conf import settings
from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient

keyvault_url = os.getenv("AZURE_KEYVAULT_URL")

#for authentication to kv
#credential = ManagedIdentityCredential(client_id="773a0a2c-4c06-4172-8021-90105f94b2d8")

credential = ManagedIdentityCredential()

client = SecretClient(vault_url=keyvault_url, credential=credential)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# DJANGO_SECRET_KEY = client.get_secret("DJANGOSECRETKEY").value
DJANGO_SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['apptravelplannerak2025.azurewebsites.net','localhost','127.0.0.1','169.254.129.3','travelplanner-app.ashysand-6f6e11a9.francecentral.azurecontainerapps.io','ak-travelplanner-cdso-dcr-01-htf9b6hbaphpc8cd.francecentral-01.azurewebsites.net']


CSRF_TRUSTED_ORIGINS = [
    'https://apptravelplannerak2025.azurewebsites.net',
    "https://ak-travelplanner-cdso-dcr-01-htf9b6hbaphpc8cd.francecentral-01.azurewebsites.net",
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trips',
]

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'route_list'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'travelplanner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travelplanner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# BASE_DIR = Path(__file__).resolve().parent.parent

# # DATABASE CONFIGURATION
# if os.environ.get("DB_ENGINE") == "mysql":
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.mysql",
#             "NAME": os.environ.get("DB_NAME"),
#             "USER": os.environ.get("DB_USER"),
#             "PASSWORD": os.environ.get("DB_PASSWORD"),
#             "HOST": os.environ.get("DB_HOST"),
#             "PORT": os.environ.get("DB_PORT", "3306"),
#         }
#     }
# else:
#     # Default to SQLite for local/testing
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db.sqlite3",
#         }
#     }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASE_NAME = client.get_secret("DBNAME").value
DATABASE_USER = client.get_secret("DBUSER").value
DATABASE_PASSWORD = client.get_secret("DBPASSWORD").value
DATABASE_HOST = client.get_secret("DBHOST").value
DATABASE_PORT = client.get_secret("DBPORT").value

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,  # Azure requires user@host format
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
        'OPTIONS': {
            'ssl': {'ca': '/etc/ssl/certs/BaltimoreCyberTrustRoot.crt.pem'},
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'travelplannerdb',
#         'USER': 'akadmin',  # Azure requires user@host format
#         'PASSWORD': 'ADMINpassword01',
#         'HOST': 'travelplannerdb.mysql.database.azure.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'ssl': {'ca': '/etc/ssl/certs/BaltimoreCyberTrustRoot.crt.pem'},
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }



# BASE_DIR = Path(__file__).resolve().parent.parent

# DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')

# if DB_ENGINE == 'mysql':
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': os.environ.get('DB_NAME', 'travelplanner'),
#             'USER': os.environ.get('DB_USER', 'root'),
#             'PASSWORD': os.environ.get('DB_PASSWORD', ''),
#             'HOST': os.environ.get('DB_HOST', 'localhost'),
#             'PORT': os.environ.get('DB_PORT', '3306'),
#             'OPTIONS': {
#                 'ssl': {'ca': '/etc/ssl/certs/BaltimoreCyberTrustRoot.crt.pem'},
#                 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             },
#         }
#     }
# else:
#     # fallback to SQLite for local testing
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / "db.sqlite3",
#         }
#     }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n//

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)@
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATIC_DIRS = [
#     os.path.join(BASE_DIR, 'static')
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Media files ---
# Azure Blob Storage configuration
# --- Media files ---
# Azure Blob Storage configuration

if os.environ.get("CI") == "true":
    # Local storage for CI/CD tests
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    # Azure Blob Storage for production
    AZURE_ACCOUNT_NAME = "akcdsoprojectsa01"
    AZURE_STORAGE_ACCOUNT_KEY = client.get_secret("AZURESTORAGEACCOUNTKEY").value
    AZURE_CONTAINER = "mediauploads"

    DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
    STATICFILES_STORAGE = "storages.backends.azure_storage.AzureStorage"
    AZURE_STORAGE_ACCOUNT_NAME = AZURE_ACCOUNT_NAME
    AZURE_STORAGE_ACCOUNT_KEY = AZURE_STORAGE_ACCOUNT_KEY
    AZURE_CONTAINER = AZURE_CONTAINER

    MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"


# Optional: Use custom domain for static media
# AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"

# URL for serving static files (can also use custom domain)
#MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"

# Static files configuration (optional, you can use Azure for static as well)
#STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'
